//
//  Constants.h
//  Haima
//
//  Created by Lei Perry on 4/9/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#define TIME_ENTRY_TIME_OFFSET_PREFIX 11
#define TIME_ENTRY_TIME_OFFSET_SUFFIX 29
#define TIME_ENTRY_PIXELS_PER_TIME_OFFSET 18

#define TIME_ENTRY_VERTICAL_MIDDLE_Y 345

#define TIME_ENTRY_PICTURE_WIDTH 140.0f
#define TIME_ENTRY_PICTURE_HEIGHT 92.0f
#define TIME_OFFSET_THRESHOLD 13
#define TIME_ENTRY_VERTICAL_OFFSET_FROM_MIDDLE 50